defaults:
  - base_train
  - _self_

epochs: 1
lr: 1e-4
batch_size: 8
optimizer: adam
scheduler: none
weight_decay: 1e-4
momentum: 0.9

use_similarity: false
similarity_loss: "none"
similarity_sampler: "none"
