stages:
  fetch:
    cmd: uv run python -m feral_vision.data.fetch
    outs:
      - data/raw

  preprocess:
    cmd: uv run python -m feral_vision.data.transforms
    deps:
      - data/raw
    outs:
      - data/processed

  augment:
    cmd: uv run python -m feral_vision.data.augmentations
    deps:
      - data/processed
    outs:
      - data/augmented
