stages:
  fetch:
    cmd: uv run python -m feral_segmentor.data.fetch
    outs:
      - data/raw

  augment:
    cmd: uv run python -m feral_segmentor.data.augmentations
    deps:
      - data/raw
    outs:
      - data/augmented

  preprocess:
    cmd: uv run python -m feral_segmentor.data.transforms
    deps:
      - data/raw
    outs:
      - data/processed

  train:
    cmd: uv run python -m feral_segmentor.pipelines.base_segmentation_pipeline
    deps:
      - data/processed
      - conf
    outs:
      - models/registry/best.pt

  evaluate:
    cmd: uv run python -m feral_segmentor.pipelines.evaluate_segmentation_pipeline
    deps:
      - models/registry/best.pt
    metrics:
      - metrics.json
